# Generated by Django 4.1.3 on 2024-02-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrganiserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeBookingsModel',
            fields=[
                ('booked_on', models.DateField(auto_created=True)),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'attendee_bookings',
            },
        ),
        migrations.CreateModel(
            name='AttendeeDetailsModel',
            fields=[
                ('attendee_created_on', models.DateField(auto_created=True)),
                ('attendee_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendee_name', models.CharField(max_length=100)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('attendee_phone', models.CharField(max_length=20)),
                ('attendee_username', models.CharField(max_length=50)),
                ('attendee_password', models.CharField(max_length=20)),
                ('attendee_role', models.CharField(max_length=50)),
                ('attendee_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'attendee_details',
            },
        ),
        migrations.CreateModel(
            name='AttendeeImagesModel',
            fields=[
                ('attendee_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendee_image', models.ImageField(null=True, upload_to='images/')),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendeeApp.attendeedetailsmodel')),
            ],
            options={
                'db_table': 'attendee_image_table',
            },
        ),
        migrations.CreateModel(
            name='AttendeeFeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendee_feedback', models.CharField(max_length=200)),
                ('attendee_rating', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendeeApp.attendeebookingsmodel')),
            ],
            options={
                'db_table': 'attendee_feedback',
            },
        ),
        migrations.AddField(
            model_name='attendeebookingsmodel',
            name='attendee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendeeApp.attendeedetailsmodel'),
        ),
        migrations.AddField(
            model_name='attendeebookingsmodel',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganiserApp.eventmodel'),
        ),
        migrations.AddField(
            model_name='attendeebookingsmodel',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganiserApp.eventticketmodel'),
        ),
    ]
