# Generated by Django 4.1.3 on 2024-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeedetailsmodel',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendeedetailsmodel',
            name='attendee_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attendeedetailsmodel',
            name='attendee_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
