# Generated by Django 4.1.3 on 2024-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendeeApp', '0002_alter_attendeedetailsmodel_attendee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeedetailsmodel',
            name='attendee_created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
