# Generated by Django 4.1.3 on 2024-03-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendeeApp', '0003_alter_attendeedetailsmodel_attendee_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeedetailsmodel',
            name='attendee_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
