# Generated by Django 4.1.3 on 2024-02-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetailsModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=20)),
                ('admin_phone', models.CharField(max_length=20)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'admin_details',
            },
        ),
        migrations.CreateModel(
            name='EventTypeModel',
            fields=[
                ('event_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'event_type_table',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'table_state',
            },
        ),
        migrations.CreateModel(
            name='EventTypeImageModel',
            fields=[
                ('event_type_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type_image', models.ImageField(null=True, upload_to='images/')),
                ('event_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.eventtypemodel')),
            ],
            options={
                'db_table': 'event_type_image_table',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.statemodel')),
            ],
            options={
                'db_table': 'table_city',
            },
        ),
    ]
