# Generated by Django 4.1.3 on 2024-02-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganiserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_description',
            field=models.TextField(),
        ),
    ]
