# Generated by Django 4.1.3 on 2024-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganiserApp', '0005_alter_organiserdetailsmodel_organiser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiserdetailsmodel',
            name='organiser_created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
